core/urls.py
from django.urls import path

from .views import (CreateVote, MovieDetail, MovieImageUpload, MovieList,
                    PersonDetail, TopMovies, TopRatedMovies, UpdateVote)

app_name = "core"

urlpatterns = [
    path("movies", MovieList.as_view(), name="movie_list"),
    path("movies/top", TopMovies.as_view(), name="top_movies"),
    path("movies/rated", TopRatedMovies.as_view(), name="top_rated"),
    path("movie/<int:pk>", MovieDetail.as_view(), name="movie_detail"),
    path("movie/<int:movie_id>/vote", CreateVote.as_view(), name="create_vote"),
    path(
        "movie/<int:movie_id>/image/upload",
        MovieImageUpload.as_view(),
        name="movie_image_upload",
    ),
    path(
        "movie/<int:movie_id>/vote/<int:pk>",
        UpdateVote.as_view(),
        name="update_vote",
    ),
    path("person/<int:pk>", PersonDetail.as_view(), name="person_detail"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

import core.urls
import user.urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include(user.urls, namespace="user")),
    path("", include(core.urls, namespace="core")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from user import views

app_name = "user"
urlpatterns = [
    path("register", views.RegisterView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

templates/includes/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'core:movie_list' %}">Django Movie DB</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li><a class="nav-link" href="{% url 'core:top_movies' %}">Top Movies</a>
                </li>
                <li><a class="nav-link" href="{% url 'core:top_rated' %}">Top Rated
                    Movies</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li><a class="nav-link" href="{% url 'user:logout' %}">Log out</a></li>
                {% else %}
                    <li><a class="nav-link" href="{% url 'user:login' %}">Log in</a></li>
                    <li><a class="nav-link" href="{% url 'user:register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>