core/urls.py
from django.urls import path

from .views import (CreateVote, MovieDetail, MovieImageUpload, MovieList,
                    PersonDetail, TopMovies, TopRatedMovies, UpdateVote)

app_name = "core"

urlpatterns = [
    path("movies", MovieList.as_view(), name="movie_list"),
    path("movies/top", TopMovies.as_view(), name="top_movies"),
    path("movies/rated", TopRatedMovies.as_view(), name="top_rated"),
    path("movie/<int:pk>", MovieDetail.as_view(), name="movie_detail"),
    path("movie/<int:movie_id>/vote", CreateVote.as_view(), name="create_vote"),
    path(
        "movie/<int:movie_id>/image/upload",
        MovieImageUpload.as_view(),
        name="movie_image_upload",
    ),
    path(
        "movie/<int:movie_id>/vote/<int:pk>",
        UpdateVote.as_view(),
        name="update_vote",
    ),
    path("person/<int:pk>", PersonDetail.as_view(), name="person_detail"),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

import core.urls
import user.urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include(user.urls, namespace="user")),
    path("", include(core.urls, namespace="core")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from uuid import uuid4

from django.conf import settings
from django.db import models
from django.db.models.aggregates import Sum


class PersonManager(models.Manager):
    def all_with_prefetch_movies(self):
        qs = self.get_queryset()
        return qs.prefetch_related("directed", "writing_credits", "role_set__movie")


class Person(models.Model):
    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140)
    born = models.DateField()
    died = models.DateField(null=True, blank=True)

    objects = PersonManager()

    class Meta:
        ordering = ("first_name", "last_name")

    def __str__(self):
        if self.died:
            return f"{self.first_name} {self.last_name} ({self.born}-{self.died})"
        return f"{self.first_name} {self.last_name} ({self.born})"


def movie_directory_path_with_uuid(instance, filename):
    return f"{instance.movie_id}/{uuid4()}.{filename.split('.')[-1]}"


class MovieImage(models.Model):
    image = models.ImageField(upload_to=movie_directory_path_with_uuid)
    uploaded = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey("Movie", on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.movie


class MovieManager(models.Manager):
    def all_with_related_persons(self):
        qs = self.get_queryset()
        qs = qs.select_related("director")
        qs = qs.prefetch_related("writers", "actors")
        return qs

    def all_with_related_persons_and_score(self):
        qs = self.all_with_related_persons()
        qs = qs.annotate(score=Sum("vote__value"))
        return qs

    def top_movies(self, limit=10):
        qs = self.get_queryset()
        qs = qs.annotate(vote_sum=Sum("vote__value"))
        qs = qs.exclude(vote_sum=None)
        qs = qs.order_by("-vote_sum")
        qs = qs[:limit]
        return qs


class Movie(models.Model):
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED, "NR - Not Rated"),
        (RATED_G, "G - General Audiences"),
        (RATED_PG, "PG - Parental Guidance " "Suggested"),
        (RATED_R, "R - Restricted"),
    )

    title = models.CharField(max_length=140)
    plot = models.TextField()
    year = models.PositiveIntegerField()
    rating = models.IntegerField(choices=RATINGS, default=NOT_RATED)
    runtime = models.PositiveIntegerField()
    website = models.URLField(blank=True)
    director = models.ForeignKey(
        to="Person",
        null=True,
        on_delete=models.SET_NULL,
        related_name="directed",
        blank=True,
    )
    writers = models.ManyToManyField(
        to="Person", related_name="writing_credits", blank=True
    )
    actors = models.ManyToManyField(
        to="Person", through="Role", related_name="acting_credits", blank=True
    )

    objects = MovieManager()

    class Meta:
        ordering = ("-year", "title")

    def __str__(self):
        return f"{self.title} ({self.year})"


class Role(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=140)

    def __str__(self):
        return f"{self.movie_id} {self.person_id} {self.name}"

    class Meta:
        unique_together = ("movie", "person", "name")


class VoteManager(models.Manager):
    def get_vote_or_unsaved_blank_vote(self, movie, user):
        try:
            return Vote.objects.get(movie=movie, user=user)
        except Vote.DoesNotExist:
            return Vote(movie=movie, user=user)


class Vote(models.Model):
    UP = 1
    DOWN = -1
    VALUE_CHOICES = ((UP, "Up vote"), (DOWN, "Down vote"))

    value = models.SmallIntegerField(
        choices=VALUE_CHOICES,
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    voted_on = models.DateTimeField(auto_now=True)

    objects = VoteManager()

    class Meta:
        unique_together = ("user", "movie")

core/forms.py
from django import forms
from django.contrib.auth import get_user_model

from core.models import Movie, MovieImage, Vote


class VoteForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput, queryset=get_user_model().objects.all(), disabled=True
    )
    movie = forms.ModelChoiceField(
        widget=forms.HiddenInput, queryset=Movie.objects.all(), disabled=True
    )
    value = forms.ChoiceField(
        label="Vote", widget=forms.RadioSelect, choices=Vote.VALUE_CHOICES
    )

    class Meta:
        model = Vote
        fields = ("value", "user", "movie")


class MovieImageForm(forms.ModelForm):
    movie = forms.ModelChoiceField(
        widget=forms.HiddenInput, queryset=Movie.objects.all(), disabled=True
    )
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput, queryset=get_user_model().objects.all(), disabled=True
    )

    class Meta:
        model = MovieImage
        fields = ("image", "user", "movie")

core/views.py
import logging

import django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from core.forms import MovieImageForm, VoteForm
from core.mixins import CachePageVaryOnCookieMixin
from core.models import Movie, MovieImage, Person, Vote

logger = logging.getLogger(__name__)


class PersonDetail(DetailView):
    queryset = Person.objects.all_with_prefetch_movies()


class MovieList(CachePageVaryOnCookieMixin, ListView):
    model = Movie
    paginate_by = 5

    def get_context_data(self, **kwargs):
        ctx = super(MovieList, self).get_context_data(**kwargs)
        page = ctx["page_obj"]
        paginator = ctx["paginator"]
        ctx["page_is_first"] = page.number == 1
        ctx["page_is_last"] = page.number == paginator.num_pages
        return ctx


class MovieDetail(DetailView):
    queryset = Movie.objects.all_with_related_persons_and_score()

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["image_form"] = self.movie_image_form()
        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_unsaved_blank_vote(
                movie=self.object, user=self.request.user
            )
            if vote.id:
                vote_form_url = reverse(
                    "core:update_vote",
                    kwargs={"movie_id": vote.movie.id, "pk": vote.id},
                )
            else:
                vote_form_url = reverse(
                    "core:create_vote", kwargs={"movie_id": self.object.id}
                )
            vote_form = VoteForm(instance=vote)
            ctx["vote_form"] = vote_form
            ctx["vote_form_url"] = vote_form_url
        return ctx

    def movie_image_form(self):
        if self.request.user.is_authenticated:
            return MovieImageForm()
        return None


class TopMovies(ListView):
    template_name = "core/top_movies_list.html"
    model = MovieImage

    def get_queryset(self):
        return MovieImage.objects.all()[:8]


class TopRatedMovies(ListView):
    template_name = "core/top_rated_list.html"

    def get_queryset(self):
        limit = 10
        key = "top_movies_%s" % limit
        cached_qs = cache.get(key)
        if cached_qs:
            same_django = cached_qs._django_version == django.get_version()
            if same_django:
                return cached_qs
        qs = Movie.objects.top_movies(limit=limit)
        cache.set(key, qs)
        return qs


class MovieImageUpload(LoginRequiredMixin, CreateView):
    form_class = MovieImageForm

    def get_initial(self):
        initial = super().get_initial()
        initial["user"] = self.request.user.id
        initial["movie"] = self.kwargs["movie_id"]
        return initial

    def render_to_response(self, context, **response_kwargs):
        movie_id = self.kwargs["movie_id"]
        movie_detail_url = reverse("core:movie_detail", kwargs={"pk": movie_id})
        return redirect(to=movie_detail_url)

    def get_success_url(self):
        movie_id = self.kwargs["movie_id"]
        movie_detail_url = reverse("core:movie_detail", kwargs={"pk": movie_id})
        return movie_detail_url


class CreateVote(LoginRequiredMixin, CreateView):
    form_class = VoteForm

    def get_initial(self):
        initial = super().get_initial()
        initial["user"] = self.request.user.id
        initial["movie"] = self.kwargs["movie_id"]
        return initial

    def render_to_response(self, context, **response_kwargs):
        movie_id = context["object"].id
        movie_detail_url = reverse("core:movie_detail", kwargs={"pk": movie_id})
        return redirect(to=movie_detail_url)

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse("core:movie_detail", kwargs={"pk": movie_id})


class UpdateVote(LoginRequiredMixin, UpdateView):
    form_class = VoteForm
    queryset = Vote.objects.all()

    def get_object(self, queryset=None):
        vote = super().get_object(queryset)
        user = self.request.user
        if vote.user != user:
            raise PermissionDenied("cannot change another users vote")
        return vote

    def render_to_response(self, context, **response_kwargs):
        movie_id = context["object"].id
        movie_detail_url = reverse("core:movie_detail", kwargs={"pk": movie_id})
        return redirect(to=movie_detail_url)

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse("core:movie_detail", kwargs={"pk": movie_id})

core/templates/core/movie_detail.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
    {{ object.title }} - {{ block.super }}
{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-md-6">
            <h1>{{ object }}</h1>
            <p>{{ object.plot }}</p>
            <p>Directed by: {{ object.director }}</p>
            <p>Written by: {{ object.writers.all|unordered_list }}</p>
            <h2>Actors</h2>
            <ul>
                {% for credit in object.role_set.all %}
                    <li>
                        <a href="{% url 'core:person_detail' pk=credit.person.id %}">{{ credit.person }} {{ credit.billing }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-md-3">
            <ul class="movie-image list-inline">
                {% for i in object.movieimage_set.all %}
                    <li class="list-inline-item mb-3">
                        <img src="{{ i.image.url }}" alt="{{ i.movie }}">
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-md-3">
            This movie is rated: <span
                class="badge badge-primary">{{ object.get_rating_display }}</span>
            <h2>
                Score: {{ object.score|default_if_none:"TBD" }}
            </h2>
            {% if image_form %}
                <h2>Upload New Image</h2>
                <form method="post" enctype="multipart/form-data"
                      action="{% url 'core:movie_image_upload' movie_id=object.id %}"
                      novalidate>
                    {% csrf_token %}
                    {{ image_form|crispy }}
                    <p>
                        <button class="btn btn-outline-primary btn-sm">Upload</button>
                    </p>
                </form>
            {% endif %}
            {% if vote_form %}
                <form method="post" action="{{ vote_form_url }}" novalidate>
                    {% csrf_token %}
                    {{ vote_form|crispy }}
                    <button class="btn btn-outline-primary btn-sm">Vote</button>
                </form>
            {% else %}
                <p>Log in to vote for this movie</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

core/templates/core/movie_list.html
{% extends 'base.html' %}

{% block title %}
    All Movies
{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center mb-5">All Movies</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <ul>
                {% for movie in object_list %}
                    <li class="mb-3">
                        <a href="{% url 'core:movie_detail' pk=movie.id %}"
                           class="btn btn-outline-primary">
                            {{ movie.title }}
                        </a>
                        <p class="mt-3">{{ movie.plot }}</p>
                    </li>
                {% endfor %}
            </ul>
            {% if is_paginated %}
                <nav class="mt-4 ml-4">
                    <ul class="pagination pagination-sm">
                        <li class="page-item">
                            <a href="{% url 'core:movie_list' %}?page=1"
                               class="page-link">First</a>
                        </li>
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a href="{% url 'core:movie_list' %}?page={{ page_obj.previous_page_number }}"
                                   class="page-link">{{ page_obj.previous_page_number }}</a>
                            </li>
                        {% endif %}
                        <li class="page-item active">
                            <a href="{% url 'core:movie_list' %}?page={{ page_obj.number }}"
                               class="page-link">{{ page_obj.number }}</a>
                        </li>
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a href="{% url 'core:movie_list' %}?page={{ page_obj.next_page_number }}"
                                   class="page-link">{{ page_obj.next_page_number }}</a>
                            </li>
                        {% endif %}
                        <li class="page-item">
                            <a href="{% url 'core:movie_list' %}?page=last"
                               class="page-link">Last</a>
                        </li>
                    </ul>
                </nav>
                </div>
                </div>
            {% endif %}
{% endblock %}

core/templates/core/person_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.first_name }}
    {{ object.last_name }}
{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h1>{{ object }}</h1>
            <h2>Actor</h2>
            <ul>
                {% for role in object.role_set.all %}
                    <li>
                        <a href="{% url 'core:movie_detail' role.movie.id %}">
                            {{ role.movie }}
                        </a>
                        {{ role.billing }}
                    </li>
                {% endfor %}
            </ul>
            <h2>Writer</h2>
            <ul>
                {% for movie in object.writing_credits.all %}
                    <li>
                        <a href="{% url 'core:movie_detail' movie.id %}">
                            {{ movie }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
            <h2>Director</h2>
            <ul>
                {% for movie in object.directed.all %}
                    <li>
                        <a href="{% url 'core:movie_detail' movie.id %}">
                            {{ movie }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

core/templates/core/top_movies_list.html
{% extends "base.html" %}

{% block title %}
    Top Movies
{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center mb-5">Top Movies</h1>
        </div>
    </div>
    <div class="row">
        {% for m in object_list %}
            <div class="col-md-3">
                <div class="card mb-5">
                    <img src="{{ m.image.url }}"
                         class="card-img-top movie-image-thumb"
                         alt="{{ m.movie }}">
                    <div class="card-body text-center">
                        <a href="{% url "core:movie_detail" m.movie_id %}"
                           class="btn btn-outline-primary brn-sm">
                            {{ m.movie }}</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

core/templates/core/top_rated_list.html
{% extends "base.html" %}
{% load cache %}

{% block title %}
    Top Rated Movies
{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <header class="text-center">
                <h1>Top Rated Movies</h1>
                <h2 class="mb-4">Highest rated movie at #1</h2>
            </header>
            {% cache 300 top10 %}
                <ol>
                    {% for movie in object_list %}
                        <li class="mb-3">
                            <a href="{% url "core:movie_detail" pk=movie.id %}">
                                {{ movie.title }}</a>
                        </li>
                    {% endfor %}
                </ol>
            {% endcache %}
        </div>
    </div>
{% endblock %}